apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-despacho-deployment  # <-- Este nombre debe coincidir con tu 'kubectl rollout restart'
  labels:
    app: ms-despacho
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-despacho
  template:
    metadata:
      labels:
        app: ms-despacho
    spec:
      containers:
        - name: ms-despacho
          image: 615406795391.dkr.ecr.us-east-1.amazonaws.com/ms-despacho:latest
          ports:
            - containerPort: 8080
          # ⬇️ AGREGA ESTE BLOQUE DE VARIABLES DE ENTORNO ⬇️
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://tienda-db.tienda:3306/tienda_perritos"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: ms-despacho-service # <-- Nombre DNS interno para que otros ms lo llamen
spec:
  type: ClusterIP # Tipo interno (invisible desde internet, protegido dentro del clúster)
  selector:
    app: ms-despacho
  ports:
    - port: 8080
      targetPort: 8081
