apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-venta-deployment
  labels:
    app: ms-venta
spec:
  replicas: 1 # Recuerda dejarlo en 1 para no saturar la RAM de AWS Academy
  selector:
    matchLabels:
      app: ms-venta
  template:
    metadata:
      labels:
        app: ms-venta
    spec:
      containers:
        - name: ms-venta
          image: 615406795391.dkr.ecr.us-east-1.amazonaws.com/tienda-backend:latest
          ports:
            - containerPort: 8080
          # ⬇️ AGREGA ESTE BLOQUE DE VARIABLES DE ENTORNO ⬇️
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://tienda-db.tienda:3306/tienda_perritos"
            - name: SPRING_DATASOURCE_USERNAME
              value: "alumno"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "alumno123"
          resources:
              requests:
                cpu: "50m"
                memory: "128Mi"
              limits:
                cpu: "500m"
                memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: ms-venta-service
spec:
  type: ClusterIP
  selector:
    app: ms-venta
  ports:
    - port: 8080
      targetPort: 8080
